-- MySQL Script generated by MySQL Workbench
-- Sat Mar 22 14:18:25 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema fibrosis_v01
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fibrosis_v01` DEFAULT CHARACTER SET utf8 ;
USE `fibrosis_v01` ;

-- -----------------------------------------------------
-- Table `fibrosis_v01`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fibrosis_v01`.`admin` (
  `id_admin` VARCHAR(10) NOT NULL,
  `nombre_admin` VARCHAR(45) NULL,
  `contrasena_admin` BLOB NOT NULL,
  PRIMARY KEY (`id_admin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fibrosis_v01`.`doctor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fibrosis_v01`.`doctor` (
  `id_doc` VARCHAR(10) NOT NULL,
  `nombre_doc` VARCHAR(45) NULL,
  `contrasena_doc` VARCHAR(45) NULL,
  `id_adminCreador` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id_doc`),
  INDEX `id_adminCreador_idx` (`id_adminCreador` ASC) VISIBLE,
  CONSTRAINT `id_adminCreador`
    FOREIGN KEY (`id_adminCreador`)
    REFERENCES `fibrosis_v01`.`admin` (`id_admin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
KEY_BLOCK_SIZE = 1;


-- -----------------------------------------------------
-- Table `fibrosis_v01`.`expediente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fibrosis_v01`.`expediente` (
  `nss` VARCHAR(15) NOT NULL,
  `sexo` TINYINT NULL,
  `fecha_creacion` TIMESTAMP NOT NULL,
  `fecha_nacimiento` DATETIME NULL,
  `id_docCreador` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`nss`),
  INDEX `id_docCreador_idx` (`id_docCreador` ASC) VISIBLE,
  CONSTRAINT `id_docCreador`
    FOREIGN KEY (`id_docCreador`)
    REFERENCES `fibrosis_v01`.`doctor` (`id_doc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fibrosis_v01`.`estudio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fibrosis_v01`.`estudio` (
  `fecha` TIMESTAMP NOT NULL,
  `nss_expediente` VARCHAR(15) NOT NULL,
  `descripcion` TEXT NULL,
  `volumen_automatico` FLOAT NULL,
  `volumen_manual` FLOAT NULL,
  UNIQUE INDEX `fecha_UNIQUE` (`fecha` ASC) VISIBLE,
  PRIMARY KEY (`fecha`, `nss_expediente`),
  INDEX `nss_expediente_idx` (`nss_expediente` ASC) VISIBLE,
  CONSTRAINT `nss_expediente`
    FOREIGN KEY (`nss_expediente`)
    REFERENCES `fibrosis_v01`.`expediente` (`nss`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fibrosis_v01`.`tomografia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fibrosis_v01`.`tomografia` (
  `nss_exp` VARCHAR(15) NOT NULL,
  `fecha_estudio` TIMESTAMP NOT NULL,
  `num_tomo` INT NOT NULL,
  `imagen` BLOB NULL,
  PRIMARY KEY (`nss_exp`, `fecha_estudio`, `num_tomo`),
  INDEX `fecha_estudio_idx` (`fecha_estudio` ASC) VISIBLE,
  CONSTRAINT `nss_exp`
    FOREIGN KEY (`nss_exp`)
    REFERENCES `fibrosis_v01`.`expediente` (`nss`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fecha_estudio`
    FOREIGN KEY (`fecha_estudio`)
    REFERENCES `fibrosis_v01`.`estudio` (`fecha`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `idx_num_tomo` ON `fibrosis_v01`.`tomografia` (`num_tomo`);

-- -----------------------------------------------------
-- Table `fibrosis_v01`.`mascara`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fibrosis_v01`.`mascara` (
  `nss_exp` VARCHAR(15) NOT NULL,
  `fecha_estudio` TIMESTAMP NOT NULL,
  `num_tomo` INT NOT NULL,
  `tipo` ENUM('automatica', 'manual') NOT NULL,
  `clase` ENUM('pulmon', 'fibrosis', 'fondo') NOT NULL,
  `coordenadas` JSON NULL,
  PRIMARY KEY (`nss_exp`, `fecha_estudio`, `num_tomo`, `tipo`, `clase`),
  INDEX `fecha_est_idx` (`fecha_estudio` ASC) VISIBLE,
  INDEX `num_tomo_idx` (`num_tomo` ASC) VISIBLE,
  CONSTRAINT `fk_nss_exp`
    FOREIGN KEY (`nss_exp`)
    REFERENCES `fibrosis_v01`.`expediente` (`nss`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fecha_estudio`
    FOREIGN KEY (`fecha_estudio`)
    REFERENCES `fibrosis_v01`.`estudio` (`fecha`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_num_tomo`
    FOREIGN KEY (`num_tomo`)
    REFERENCES `fibrosis_v01`.`tomografia` (`num_tomo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `fibrosis_v01`.`modifica_doc_estudio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fibrosis_v01`.`modifica_doc_estudio` (
  `id_doc` VARCHAR(10) NOT NULL,
  `nss_exp` VARCHAR(15) NOT NULL,
  `fecha_estudio` TIMESTAMP NOT NULL,
  `fecha_ajuste_manual` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id_doc`, `nss_exp`, `fecha_estudio`),
  INDEX `fecha_estudio_idx` (`fecha_estudio` ASC) VISIBLE,
  CONSTRAINT `fk_id_doc`
    FOREIGN KEY (`id_doc`)
    REFERENCES `fibrosis_v01`.`doctor` (`id_doc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_nss_exp_mod`
    FOREIGN KEY (`nss_exp`)
    REFERENCES `fibrosis_v01`.`expediente` (`nss`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fecha_estudio_mod`
    FOREIGN KEY (`fecha_estudio`)
    REFERENCES `fibrosis_v01`.`estudio` (`fecha`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
